---
# tasks file for namespace

- name: Create namespace record
  snow_record:
    username: admin
    password: MDD9iHmvdhW3
    instance: dev88478
    state: present
    lookup_field: name
    table: cmdb_ci_docker_container
    data:
      name: 'namespace-{{ meta.name }}'
