apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespaces.itsm.example.com
spec:
  group: itsm.example.com
  names:
    kind: Namespace
    listKind: NamespaceList
    plural: namespaces
    singular: namespace
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
