---
# tasks file for namespace

- name: Fetch namespace sys_id label
  set_fact:
    project: "{{ lookup('k8s', api_version='v1', kind='Namespace', resource_name=meta.name) }}"

- set_fact:
    sys_id: '{{ project.metadata.labels.sys_id }}'
  ignore_errors: true

- set_fact:
    sys_id: null
  when: sys_id is not defined

- name: Update namespace record as absent
  snow_record:
    instance: "{{ lookup('env','SNOW_INSTANCE') }}"
    username: "{{ lookup('env','SNOW_USER') }}"
    password: "{{ lookup('env','SNOW_PASS') }}"
    state: present
    number: '{{ sys_id }}'
    table: cmdb_ci_docker_container
    lookup_field: sys_id
    data:
      name: 'namespace-{{ meta.name }}'
      status: 'absent: {{ sys_id }}'
  register: namespace_record
